export const ACTION_TYPES = [
  "create",
  "update",
  "delete",
  "read",
  "login",
  "logout",
  "export",
  "validate",
  "reject",
  "share",
  "other",
] as const;

export type ActionType = (typeof ACTION_TYPES)[number];

export const ACTION_TYPE_LABELS: Record<ActionType, string> = {
  create: "Création",
  update: "Modification",
  delete: "Suppression",
  read: "Consultation",
  login: "Connexion",
  logout: "Déconnexion",
  export: "Export",
  validate: "Validation",
  reject: "Rejet",
  share: "Partage",
  other: "Autre",
};

/** Codes d'actions métier (ressource.action) */
export const ACTIONS = {
  USER_CREATE: "user.create",
  USER_UPDATE: "user.update",
  USER_DELETE: "user.delete",
  USER_VIEW: "user.view",
  ABSENCE_CREATE: "absence.create",
  ABSENCE_ADMIN_BYPASS: "absence.admin_bypass",
  ABSENCE_DELETE: "absence.delete",
  ABSENCE_APPROVE: "absence.approve",
  ABSENCE_REJECT: "absence.reject",
  GED_FILE_UPLOAD: "ged.file.upload",
  GED_FOLDER_CREATE: "ged.folder.create",
  GED_FILE_UPDATE: "ged.file.update",
  GED_FOLDER_UPDATE: "ged.folder.update",
  GED_FILE_DELETE: "ged.file.delete",
  GED_FOLDER_DELETE: "ged.folder.delete",
  GED_FILE_DOWNLOAD: "ged.file.download",
  GED_FILE_SHARE: "ged.file.share",
  CONVOCATION_CREATE: "convocation.create",
  CONVOCATION_UPDATE: "convocation.update",
  CONVOCATION_DELETE: "convocation.delete",
  CONVOCATION_SEND: "convocation.send",
  CONVOCATION_RESEND: "convocation.resend",
  CONVOCATION_RESPOND: "convocation.respond",
  CONVOCATION_ACK: "convocation.ack",
  CONVOCATION_ATTENDANCE: "convocation.attendance",
  CONVOCATION_ARCHIVE: "convocation.archive",
  ABSENCE_DELEGATION_CREATE: "absence.delegation.create",
  ABSENCE_DELEGATION_REVOKE: "absence.delegation.revoke",
} as const;

export type ActionCode = (typeof ACTIONS)[keyof typeof ACTIONS];

export const ACTION_LABELS: Record<ActionCode, string> = {
  "user.create": "Création d'un utilisateur",
  "user.update": "Modification d'un utilisateur",
  "user.delete": "Suppression d'un utilisateur",
  "user.view": "Consultation d'un utilisateur",
  "absence.create": "Demande d'absence déposée",
  "absence.admin_bypass": "Absence approuvée directement (admin)",
  "absence.delete": "Demande d'absence supprimée",
  "absence.approve": "Demande d'absence approuvée",
  "absence.reject": "Demande d'absence refusée",
  "ged.file.upload": "Upload d'un document GED",
  "ged.folder.create": "Création d'un dossier GED",
  "ged.file.update": "Renommage d'un document GED",
  "ged.folder.update": "Renommage d'un dossier GED",
  "ged.file.delete": "Suppression d'un document GED",
  "ged.folder.delete": "Suppression d'un dossier GED",
  "ged.file.download": "Téléchargement d'un document GED",
  "ged.file.share": "Partage d'un document GED",
  "convocation.create": "Création d'une convocation",
  "convocation.update": "Modification d'une convocation",
  "convocation.delete": "Suppression d'une convocation",
  "convocation.send": "Envoi d'une convocation",
  "convocation.resend": "Renvoi d'une convocation à un agent",
  "convocation.respond": "Réponse à une convocation",
  "convocation.ack": "Accusé de réception d'une convocation",
  "convocation.attendance": "Émargement convocation",
  "convocation.archive": "Archivage d'une convocation",
  "absence.delegation.create": "Délégation de validation créée",
  "absence.delegation.revoke": "Délégation de validation révoquée",
};
